name: Project
labelField: name
fields:
  - type: TEXT
    id: name
    label: Name
    autoComplete: off
    defaultValue: ''
  - type: REFERENCE
    id: owner
    label: Owner
    autoComplete: off
    defaultValue: ''
  - type: JSON
    id: json_data
    label: Legacy Data
    autoComplete: off
    defaultValue: ''
