name: vercel_deployment_tests

on: deployment

jobs:
  regression:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/e2e
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          repo: kendraio-app&teamId=kendraio