name: vercel_deployment_tests

on: deployment

jobs:
  regression:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/e2e
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          repo: kendraio-app&teamId=kendraio
          cypress-record-key: ${{ secrets.CYPRESS_RECORD_KEY }}